[package]
name = "data-structures"
version = "0.1.0"
authors = ["Kirill Vasiltsov <v_kirill@yumemi.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
